services:
  playwright:
    build:
      context: pw01
    init: true
    ipc: host
    volumes:
      - ./pw01:/playwright
      - node_modules:/playwright/node_modules
      - playwright-report:/playwright/playwright-report
      - test-results:/playwright/test-results

volumes:
  node_modules:
  playwright-report:
  test-results:
