services:
  rails:
    build:
      context: .
    image: myapp:1.0.0
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundle:
