services:
  playwright:
    build: .
    init: true
    ipc: host
    volumes:
      - ./:/playwright
      - node_modules:/playwright/node_modules
      - playwright-report:/playwright/playwright-report
      - test-results:/playwright/test-results

volumes:
  node_modules:
  playwright-report:
  test-results:
