inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails

AllCops:
  TargetRailsVersion: 6.0

require:
  - './lib/rubocop/cop/custom/enumerize_boolean_binary_values.rb'

Custom/EnumerizeBooleanBinaryValues:
  Enabled: true
  Include:
    - 'app/models/**/*.rb'
