services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    environment:
      - RAILS_ENV=development

volumes:
  bundle_data:
