version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: mcp-youtube-server-app
    env_file:
      - .env
    command: node index.js

  formatter:
    build:
      context: .
      dockerfile: Dockerfile.formatter
    container_name: mcp-youtube-server-formatter
    command: bash ./format.sh
