services:
  ruby:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    volumes:
      - .:/ruby
      - bundle:/usr/local/bundle

volumes:
  bundle:
