services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: myapp:1.0.0
    volumes:
      - .:/rails
      - bundle_rails60:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundle_rails60:
