services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:1.0.1
    tty: true
    stdin_open: true
    volumes:
      - .:/rails
      - bundle_rails60:/usr/local/bundle
    ports:
      - "3000:3000"
  localstack:
    image: localstack/localstack:4.0
    ports:
      - "4566:4566"
    environment:
      DOCKER_SOCK: /var/run/docker.sock
      DEBUG: 1
    volumes:
      - ./localstack/init:/etc/localstack/init

volumes:
  bundle_rails60:
