name: Dagger Shell Example

on:
  push:

jobs:
  dagger-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dagger Shell
        uses: dagger/dagger-for-github@v8.2.0
        with:
          shell: |
            container |
              from ruby:3.2.0-slim-bullseye |
              with-exec apt-get update |
              with-exec -- apt-get install -y --no-install-recommends make gcc |
              with-exec -- gcc --version |
              stdout
