name: Dagger Shell Example

on:
  push:

jobs:
  dagger-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dagger Shell
        uses: dagger/dagger-for-github@v8.2.0
        with:
          shell: |
            container |
              from alpine |
              with-exec echo,"hello, world!" |
              stdout
