name: Playwright Tests
on:
  push:
    paths:
      - '.github/workflows/playwright.yml'
      - 'pw01/**/*'
defaults:
  run:
    working-directory: pw01
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: pw01/playwright-report/
        retention-days: 30
